package day38_exceptions;

import java.util.Scanner;

public class Exceptions02 {

	public static void main(String[] args) {
		// Kullanicidan 2 tam sayi alin ve bolumleirni yazdirin
		int count=0;
		Scanner scan = new Scanner(System.in);
		while(count<100) {
			
		
		System.out.println("Lutfen  bolunecek tamsayiyi giriniz");
		int sayi1 = scan.nextInt();
		System.out.println("Lutfen kaca bolmek istediginizi giriniz");
		int sayi2 = scan.nextInt();
		// java exceptions i handle etmek icin try-catch blogu olusturmus

		try {
			System.out.println("bolme isleminin sonucu : " + sayi1 / sayi2);

		} catch (ArithmeticException e) {
			System.out.println("Sayiyi 0 a bolemezsin");
		}
		count++;
	}
	}

}
